#!/usr/bin/env python3
"""
Manual ADR Creator — Generate ADR from explicit inputs
For decisions made outside of Simulacrum debates.
Part of Agenticana v7.0 MCP Self-Evolution System
"""
import argparse
import json
from datetime import datetime
from pathlib import Path

ADR_DIR = Path("docs/decisions")


def slugify(text: str, max_length: int = 50) -> str:
    """Convert text to URL-friendly slug."""
    slug = "-".join(text.lower().split())
    slug = "".join(c if c.isalnum() or c == "-" else "" for c in slug)
    return slug[:max_length].strip("-")


def get_next_adr_number() -> int:
    """Find the next ADR number in sequence."""
    ADR_DIR.mkdir(parents=True, exist_ok=True)
    existing = sorted(ADR_DIR.glob("ADR-*.md"))
    if not existing:
        return 1
    last = existing[-1].stem  # e.g., ADR-007
    try:
        return int(last.split("-")[1]) + 1
    except (IndexError, ValueError):
        return len(existing) + 1


def create_manual_adr(
    title: str,
    context: str,
    decision: str,
    consequences: str,
    alternatives: list = None,
    status: str = "accepted",
) -> tuple[int, str, str]:
    """
    Generate ADR from manual inputs.

    Args:
        title: Short title for the decision
        context: Background and problem statement
        decision: The actual decision made
        consequences: Expected outcomes and implications
        alternatives: List of alternative options considered
        status: Decision status (proposed, accepted, deprecated, superseded)

    Returns:
        Tuple of (adr_number, adr_content, file_path)
    """
    adr_num = get_next_adr_number()
    date_str = datetime.now().strftime("%Y-%m-%d")

    # Build ADR content
    adr_content = f"""# ADR-{adr_num:03d}: {title}

**Status:** {status.upper()}
**Date:** {date_str}
**Method:** Manual Entry (not from Simulacrum)

---

## Context

{context}

## Decision

{decision}

## Consequences

{consequences}
"""

    # Add alternatives section if provided
    if alternatives and len(alternatives) > 0:
        adr_content += "\n## Alternatives Considered\n\n"
        for i, alt in enumerate(alternatives, 1):
            adr_content += f"{i}. {alt}\n"

    # Footer
    adr_content += f"\n---\n\n*Generated by Agenticana Manual ADR Creator*\n"

    # Create filename
    slug = slugify(title)
    file_path = ADR_DIR / f"ADR-{adr_num:03d}-{slug}.md"

    return adr_num, adr_content, str(file_path)


def main():
    parser = argparse.ArgumentParser(
        description="Manual ADR Creator — Generate ADR from explicit inputs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --title "Use PostgreSQL for Database" \\
           --context "Need ACID compliance and strong consistency" \\
           --decision "PostgreSQL 15 with RLS and connection pooling" \\
           --consequences "Better data integrity, easier reporting"

  %(prog)s --title "Adopt TypeScript" \\
           --context "Growing codebase needs type safety" \\
           --decision "Migrate to TypeScript over 6 months" \\
           --consequences "Better IDE support, fewer runtime bugs" \\
           --alternative "Keep JavaScript with JSDoc" \\
           --alternative "Use Flow instead" \\
           --status accepted \\
           --json
        """
    )
    parser.add_argument("--title", required=True, help="ADR title (max 100 chars)")
    parser.add_argument("--context", required=True, help="Decision context and background")
    parser.add_argument("--decision", required=True, help="The decision made")
    parser.add_argument("--consequences", required=True, help="Expected consequences")
    parser.add_argument(
        "--alternative",
        action="append",
        dest="alternatives",
        help="Alternative option considered (can specify multiple)",
    )
    parser.add_argument(
        "--status",
        default="accepted",
        choices=["proposed", "accepted", "deprecated", "superseded"],
        help="Decision status (default: accepted)",
    )
    parser.add_argument("--json", action="store_true", help="Output JSON format")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing file")

    args = parser.parse_args()

    # Generate ADR
    adr_num, adr_content, file_path = create_manual_adr(
        title=args.title,
        context=args.context,
        decision=args.decision,
        consequences=args.consequences,
        alternatives=args.alternatives or [],
        status=args.status,
    )

    # Write to file (unless dry-run)
    if not args.dry_run:
        Path(file_path).parent.mkdir(parents=True, exist_ok=True)
        Path(file_path).write_text(adr_content, encoding="utf-8")

    # Output results
    if args.json:
        result = {
            "adr_number": adr_num,
            "file_path": file_path,
            "title": args.title,
            "status": args.status,
            "dry_run": args.dry_run,
        }
        if args.dry_run:
            result["preview"] = adr_content
        print(json.dumps(result, indent=2))
    else:
        if args.dry_run:
            print("\n" + "="*60)
            print("DRY RUN - PREVIEW ONLY")
            print("="*60)
            print(adr_content)
            print("="*60)
            print(f"\nWould create: {file_path}")
        else:
            print(f"\n✅ Generated: {file_path}")
            print(f"📄 ADR-{adr_num:03d}: {args.title}")
            print(f"📊 Status: {args.status.upper()}")


if __name__ == "__main__":
    main()
